// Fetches js/photos-manifest.json (auto-generated by the GitHub Action in
// .github/workflows/update-photo-manifest.yml) and, for any gallery that has
// real photos listed, replaces its placeholder photos with them.
//
// Galleries with no matching folder yet just keep their placeholder photos,
// so the site still looks complete before you've added real images.
async function applyPhotoManifest() {
  let manifest;
  try {
    const res = await fetch("photos-manifest.json", { cache: "no-store" });
    if (!res.ok) return;
    manifest = await res.json();
  } catch (err) {
    return; // no manifest yet, or running from file:// — keep placeholders
  }

  GALLERIES.forEach((g) => {
    const files = manifest[g.slug];
    if (files && files.length) {
      g.photos = files.map((src) => ({ src }));
      g.cover = files[0];
    }
  });
}
